Repository LouisLanganay/Zappy, pull requests merged in 2024-06, with the labels that each got.

#19 Feat/multi client ai
  IA/src/Client.py
  IA/src/Client_broadcast.py
  IA/src/Main.py
Labels: feat

#20 Feat/graphical improvement
  .gitignore
  Client/Fonts/Mario-Kart-DS.ttf
  Client/Fonts/Minecraft.ttf
  Client/Models/Egg/Egg.mtl
  Client/Models/Egg/Egg.png
  Client/Models/Eolienne/EolicOBJ.mtl
  Client/Models/Eolienne/EolicOBJ.obj
  Client/Models/Eolienne/paletas-04.png
  Client/Models/Eolienne/vegetacion paleta.png
  Client/Models/Ingot/Ingot.obj
  Client/Source/Core/Core.cpp
  Client/Source/Core/Core.hpp
  Client/Source/Exceptions.hpp
  Client/Source/Hud/AHud.cpp
  Client/Source/Hud/AHud.hpp
  Client/Source/Hud/Left/HudLeft.cpp
  Client/Source/Hud/Left/HudLeft.hpp
  Client/Source/Hud/Right/HudRight.cpp
  Client/Source/Hud/Right/HudRight.hpp
  Client/Source/Main.cpp
  Client/Source/Map/Egg/Egg.cpp
  Client/Source/Map/Egg/Egg.hpp
  Client/Source/Map/Map.cpp
  Client/Source/Map/Map.hpp
  Client/Source/Map/Player/Player.cpp
  Client/Source/Map/Player/Player.hpp
  Client/Source/Map/Tile/Tile.cpp
  Client/Source/Map/Tile/Tile.hpp
  Client/Source/Model3D/Model3D.cpp
  Client/Source/Model3D/Model3D.hpp
Labels: feat

#18 Game
  .gitignore
  Client/Fonts/Mario-Kart-DS.ttf
  Client/Fonts/Minecraft.ttf
  Client/Models/Egg/Egg.mtl
  Client/Models/Egg/Egg.png
  Client/Models/Eolienne/EolicOBJ.mtl
  Client/Models/Eolienne/EolicOBJ.obj
  Client/Models/Eolienne/paletas-04.png
  Client/Models/Eolienne/vegetacion paleta.png
  Client/Models/Ingot/Ingot.obj
  Client/Source/Core/Core.cpp
  Client/Source/Core/Core.hpp
  Client/Source/Exceptions.hpp
  Client/Source/Hud/AHud.cpp
  Client/Source/Hud/AHud.hpp
  Client/Source/Hud/Left/HudLeft.cpp
  Client/Source/Hud/Left/HudLeft.hpp
  Client/Source/Hud/Right/HudRight.cpp
  Client/Source/Hud/Right/HudRight.hpp
  Client/Source/Main.cpp
  Client/Source/Map/Egg/Egg.cpp
  Client/Source/Map/Egg/Egg.hpp
  Client/Source/Map/Map.cpp
  Client/Source/Map/Map.hpp
  Client/Source/Map/Player/Player.cpp
  Client/Source/Map/Player/Player.hpp
  Client/Source/Map/Tile/Tile.cpp
  Client/Source/Map/Tile/Tile.hpp
  Client/Source/Model3D/Model3D.cpp
  Client/Source/Model3D/Model3D.hpp
  IA/src/Client.py
  IA/src/Client_broadcast.py
  IA/src/Main.py
  Server/Makefile
  Server/include/server.h
  Server/include/server/ai_header.h
  Server/include/server/flags.h
  Server/include/server/game.h
  Server/include/server/gui.h
  Server/src/ai.c
  Server/src/ai/broadcast.c
  Server/src/ai/connect_nbr.c
  Server/src/ai/death.c
  Server/src/ai/fork.c
  Server/src/ai/forward.c
  Server/src/ai/incantation.c
  Server/src/ai/inventory.c
  Server/src/ai/left.c
  Server/src/ai/right.c
  Server/src/ai/set.c
  Server/src/ai/take.c
  Server/src/game/game.c
  Server/src/game/map.c
  Server/src/gui/ppo.c
  Server/src/payload.c
  Server/src/server.c
  Server/src/team.c
  tests/server/payload.c
  tests/server/team.c
Labels: feat

#23 Doc/readme
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Documentation/Image/Game.png
  Documentation/Zappy-Graphical.pdf
  README.md
  SECURITY.md
Labels: documentation

#24 Ai optimized
  IA/src/AI.py
  IA/src/Client.py
  IA/src/Client_broadcast.py
  IA/src/Food_duplicator.py
  IA/src/Main.py
  IA/src/ParseArgs.py
  IA/src/simple_client.py
Labels: feat

#25 Doc/readme
  Documentation/Diagram/GraphicalGraph.png
  Documentation/Diagram/GraphicalGraph.svg
  Documentation/Zappy-AI.pdf
  Documentation/Zappy-Server.pdf
  IA/Makefile
  IA/src/Client.py
  IA/src/Main.py
  README.md
Labels: documentation

#21 Feat/graphical improvement
  .gitignore
  Client/Makefile
  Client/Source/API/Api.cpp
  Client/Source/API/Api.hpp
  Client/Source/Core/Core.cpp
  Client/Source/Main.cpp
  Client/Source/Map/Map.cpp
  Client/Source/Map/Player/Player.cpp
  Client/Source/Map/Tile/Tile.cpp
Labels: feat

#29 Test/server
  Server/include/server.h
  Server/include/server/flags.h
  Server/src/ai.c
  Server/src/ai/eject.c
  Server/src/team.c
  tests/server/ai/eject.c
  tests/server/payload.c
Labels: bug

#30 fix(test/server): incantation be blocking.
  Server/src/ai.c
  Server/src/ai/incantation.c
  Server/src/game/game.c
  tests/server/payload.c
Labels: bug
